//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public Nullable<int> CourseWorkId { get; set; }
        public Nullable<System.DateTime> cd { get; set; }
        public string cb { get; set; }
        public Nullable<System.DateTime> ud { get; set; }
        public string ub { get; set; }
        public Nullable<byte> st { get; set; }
    
        public virtual CourseWork CourseWork { get; set; }
    }
}
