//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Relationship { get; set; }
        public string Gender { get; set; }
        public Nullable<int> IC { get; set; }
        public byte[] Name { get; set; }
        public string Edu { get; set; }
        public string WorkStatus { get; set; }
        public string Job { get; set; }
        public string FeildWork { get; set; }
        public string SectorJob { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<System.TimeSpan> cd { get; set; }
        public Nullable<int> cb { get; set; }
        public Nullable<System.TimeSpan> ud { get; set; }
        public Nullable<int> ub { get; set; }
        public Nullable<byte> st { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
