//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCard
    {
        public int Id { get; set; }
        public Nullable<int> Course_ModuleId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> IntakeId { get; set; }
        public Nullable<int> TrainerId { get; set; }
        public Nullable<int> ClassStudentId { get; set; }
        public Nullable<int> ModuleStandardId { get; set; }
        public Nullable<int> CourseWorkId { get; set; }
        public Nullable<System.TimeSpan> cd { get; set; }
        public Nullable<int> cb { get; set; }
        public Nullable<System.TimeSpan> ud { get; set; }
        public Nullable<int> ub { get; set; }
        public Nullable<byte> st { get; set; }
    
        public virtual ClassStudent ClassStudent { get; set; }
        public virtual Course_Module Course_Module { get; set; }
        public virtual CourseWork CourseWork { get; set; }
        public virtual Intake Intake { get; set; }
        public virtual ModuleStandard ModuleStandard { get; set; }
        public virtual Trainer Trainer { get; set; }
        public virtual Student Student { get; set; }
    }
}
