//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISv2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SISV2Entities : DbContext
    {
        public SISV2Entities()
            : base("name=SISV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<ClassStudent> ClassStudents { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Course_Module> Course_Module { get; set; }
        public virtual DbSet<CourseWork> CourseWorks { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Intake> Intakes { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<MarkType> MarkTypes { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModuleStandard> ModuleStandards { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<Package_Course> Package_Course { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<ReportCard> ReportCards { get; set; }
        public virtual DbSet<Sibling> Siblings { get; set; }
        public virtual DbSet<SPMResult> SPMResults { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<TestType> TestTypes { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
        public virtual DbSet<Year> Years { get; set; }
        public virtual DbSet<Guardian> Guardians { get; set; }
    }
}
